name: unit-test

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.mk'
      - 'Makefile'
      - '**.yaml'
      - '!src/flag_gems/experimental_ops/**'
      - '!experimental_tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.mk'
      - 'Makefile'
      - '**.yaml'
      - '!src/flag_gems/experimental_ops/**'
      - '!experimental_tests/**'

jobs:
  triage:
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      ops_stable: ${{ steps.filter.outputs.stable_ops }}
      ops_experimental: ${{ steps.filter.outputs.experimental_ops }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: changed-files
        uses: tj-actions/changed-files@v74
      - id: filter
        shell: bash
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo ${CHANGED_FILES[@]}

  build-doc:
    needs: triage
    if: ${{ needs.triage.outputs.docs == 'true' }}
    uses: ./.github/workflows/mkdocs.yaml

  blas-op-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: blas-op-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/blas-op-test.yaml

  model-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: model-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/model-test.yaml

  quick-cpu-op-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: op-test-quick-cpu-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/op-test-quick-cpu.yaml

  pointwise-op-test:
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: pointwise-op-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pointwise-op-test.yaml

  reduction-op-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: reduction-op-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/reduction-op-test.yaml

  special-op-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: special-op-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/special-op-test.yaml

  utils-test:
    needs: triage
    if: ${{ needs.triage.outputs.stable_ops == 'true' || needs.triage.outputs.stable_test == 'true' }}
    concurrency:
      group: op-utils-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/op-utils-test.yaml

  coverage:
    needs:
      - triage
      - blas-op-test
      - model-test
      - quick-cpu-op-test
      - utils-test
      - pointwise-op-test
      - reduction-op-test
      - special-op-test
    if: ${{ needs.triage.outputs.ops_stable == 'true' }}
    concurrency:
      group: coverage-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: cpu
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get python coverage
        shell: bash
        run: |
          git config --global --add safe.directory ../FlagGems
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_ID=${{ github.event.pull_request.number }}
          elif [ "${{ github.event_name }}" == "push" ]; then
            PR_NUMBER=$(git log -1 --pretty=format:'%s' | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
            PR_ID=${PR_NUMBER}
          fi
          bash tools/code_coverage/coverage.sh ${PR_ID}

      - name: Report python coverage
        shell: bash
        run: |
          git config --global --add safe.directory ../FlagGems
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_ID=${{ github.event.pull_request.number }}
          elif [ "${{ github.event_name }}" == "push" ]; then
            PR_NUMBER=$(git log -1 --pretty=format:'%s' | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
            PR_ID=${PR_NUMBER}
          fi
          bash tools/code_coverage/report_coverage.sh ${PR_ID}
